# Generated by Django 5.2.4 on 2025-08-04 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0022_channel_auto_created_channel_auto_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='m3u_logo_url',
            field=models.TextField(blank=True, help_text='Last logo URL value from M3U source', null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='m3u_name',
            field=models.CharField(blank=True, help_text='Last name value from M3U source', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='user_logo',
            field=models.ForeignKey(blank=True, help_text='User-edited logo, takes precedence over M3U logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_channels', to='dispatcharr_channels.logo'),
        ),
        migrations.AddField(
            model_name='channel',
            name='user_name',
            field=models.CharField(blank=True, help_text='User-edited name, takes precedence over M3U name', max_length=255, null=True),
        ),
    ]
